"""sales id update

Revision ID: 622268d009e1
Revises: 
Create Date: 2025-05-18 15:31:18.928734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622268d009e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('product_id', sa.BINARY(length=36), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('per_item_price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('per_item_price <= 9999.99', name='ck_per_item_price_max'),
    sa.CheckConstraint('per_item_price >= 0', name='ck_per_item_price_non_negative'),
    sa.CheckConstraint('quantity <= 99999', name='ck_quantity_max'),
    sa.CheckConstraint('quantity >= 0', name='ck_quantity_non_negative'),
    sa.CheckConstraint('total_price <= 999989000.01', name='ck_total_price_max'),
    sa.CheckConstraint('total_price >= 0', name='ck_total_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sales_id'), 'sale_items', ['sales_id'], unique=False)
    op.alter_column('sales', 'id',
               existing_type=sa.BINARY(length=16),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'id',
               existing_type=sa.Integer(),
               type_=sa.BINARY(length=16),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_sale_items_sales_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    # ### end Alembic commands ###
