"""price range update

Revision ID: 75f37465ef64
Revises: c8cfabb970d4
Create Date: 2025-05-19 02:24:55.983987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75f37465ef64'
down_revision: Union[str, None] = 'c8cfabb970d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
